# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gymcraft/gym/action/components/move_menu_item.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gymcraft/gym/action/components/move_menu_item.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3gymcraft/gym/action/components/move_menu_item.proto\x12\x13gymcraft.gym.action\"W\n\x11ProtoMoveMenuItem\x12\x12\n\nsession_id\x18\x01 \x01(\x04\x12(\n\x05moves\x18\x06 \x03(\x0b\x32\x19.gymcraft.gym.action.MoveJ\x04\x08\x02\x10\x06\"U\n\x04Move\x12\x16\n\x0esource_slot_id\x18\x01 \x01(\x05\x12\x16\n\x0etarget_slot_id\x18\x02 \x01(\x05\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x12\x0e\n\x06repeat\x18\x04 \x01(\x05\x42\x44\n-io.github.mousemeya.gymcraft.gym.action.protoB\x11MoveMenuItemProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gymcraft.gym.action.components.move_menu_item_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n-io.github.mousemeya.gymcraft.gym.action.protoB\021MoveMenuItemProtoP\001'
  _globals['_PROTOMOVEMENUITEM']._serialized_start=76
  _globals['_PROTOMOVEMENUITEM']._serialized_end=163
  _globals['_MOVE']._serialized_start=165
  _globals['_MOVE']._serialized_end=250
# @@protoc_insertion_point(module_scope)
