# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gymcraft/gym/action/components/open_menu.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gymcraft/gym/action/components/open_menu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.gymcraft/gym/action/components/open_menu.proto\x12\x13gymcraft.gym.action\"7\n\x14ProtoBlockMenuTarget\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\"*\n\x15ProtoEntityMenuTarget\x12\x11\n\tentity_id\x18\x01 \x01(\x05\"\x15\n\x13ProtoSelfMenuTarget\"\xcd\x01\n\rProtoOpenMenu\x12:\n\x05\x62lock\x18\x01 \x01(\x0b\x32).gymcraft.gym.action.ProtoBlockMenuTargetH\x00\x12<\n\x06\x65ntity\x18\x02 \x01(\x0b\x32*.gymcraft.gym.action.ProtoEntityMenuTargetH\x00\x12\x38\n\x04self\x18\x03 \x01(\x0b\x32(.gymcraft.gym.action.ProtoSelfMenuTargetH\x00\x42\x08\n\x06targetB@\n-io.github.mousemeya.gymcraft.gym.action.protoB\rOpenMenuProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gymcraft.gym.action.components.open_menu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n-io.github.mousemeya.gymcraft.gym.action.protoB\rOpenMenuProtoP\001'
  _globals['_PROTOBLOCKMENUTARGET']._serialized_start=71
  _globals['_PROTOBLOCKMENUTARGET']._serialized_end=126
  _globals['_PROTOENTITYMENUTARGET']._serialized_start=128
  _globals['_PROTOENTITYMENUTARGET']._serialized_end=170
  _globals['_PROTOSELFMENUTARGET']._serialized_start=172
  _globals['_PROTOSELFMENUTARGET']._serialized_end=193
  _globals['_PROTOOPENMENU']._serialized_start=196
  _globals['_PROTOOPENMENU']._serialized_end=401
# @@protoc_insertion_point(module_scope)
