# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gymcraft/gym/action/components/step_move.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gymcraft/gym/action/components/step_move.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.gymcraft/gym/action/components/step_move.proto\x12\x13gymcraft.gym.action\"]\n\rProtoStepMove\x12\x0f\n\x07\x66orward\x18\x01 \x01(\x02\x12\x14\n\x0cstrafe_right\x18\x02 \x01(\x02\x12\x11\n\tyaw_delta\x18\x03 \x01(\x02\x12\x0c\n\x04jump\x18\x05 \x01(\x08J\x04\x08\x04\x10\x05\x42@\n-io.github.mousemeya.gymcraft.gym.action.protoB\rStepMoveProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gymcraft.gym.action.components.step_move_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n-io.github.mousemeya.gymcraft.gym.action.protoB\rStepMoveProtoP\001'
  _globals['_PROTOSTEPMOVE']._serialized_start=71
  _globals['_PROTOSTEPMOVE']._serialized_end=164
# @@protoc_insertion_point(module_scope)
