# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gymcraft/gym/action/components/update_interesting_blocks.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gymcraft/gym/action/components/update_interesting_blocks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>gymcraft/gym/action/components/update_interesting_blocks.proto\x12\x13gymcraft.gym.action\"O\n\x1cProtoUpdateInterestingBlocks\x12\x15\n\radd_block_ids\x18\x01 \x03(\t\x12\x18\n\x10remove_block_ids\x18\x02 \x03(\tBO\n-io.github.mousemeya.gymcraft.gym.action.protoB\x1cUpdateInterestingBlocksProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gymcraft.gym.action.components.update_interesting_blocks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n-io.github.mousemeya.gymcraft.gym.action.protoB\034UpdateInterestingBlocksProtoP\001'
  _globals['_PROTOUPDATEINTERESTINGBLOCKS']._serialized_start=87
  _globals['_PROTOUPDATEINTERESTINGBLOCKS']._serialized_end=166
# @@protoc_insertion_point(module_scope)
