syntax = "proto3";

package gymcraft.gym.action;

option java_multiple_files = true;
option java_package = "io.github.mousemeya.gymcraft.gym.action.proto";
option java_outer_classname = "OpenMenuProto";

message ProtoBlockMenuTarget {
  int32 x = 1;
  int32 y = 2;
  int32 z = 3;
}

message ProtoEntityMenuTarget {
  int32 entity_id = 1;
}

message ProtoSelfMenuTarget {
}

message ProtoOpenMenu {
  oneof target {
    ProtoBlockMenuTarget block = 1;
    ProtoEntityMenuTarget entity = 2;
    ProtoSelfMenuTarget self = 3;
  }
}
