# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gymcraft/gym/observation/common/item_entity_view.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gymcraft/gym/observation/common/item_entity_view.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gymcraft.gym.observation.common import item_stack_view_pb2 as gymcraft_dot_gym_dot_observation_dot_common_dot_item__stack__view__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6gymcraft/gym/observation/common/item_entity_view.proto\x12\x18gymcraft.gym.observation\x1a\x35gymcraft/gym/observation/common/item_stack_view.proto\"\xa5\x01\n\x13ProtoItemEntityView\x12\x11\n\tentity_id\x18\x01 \x01(\x05\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\t\n\x01x\x18\x03 \x01(\x01\x12\t\n\x01y\x18\x04 \x01(\x01\x12\t\n\x01z\x18\x05 \x01(\x01\x12\x10\n\x08\x64istance\x18\x06 \x01(\x01\x12:\n\x04item\x18\x07 \x01(\x0b\x32,.gymcraft.gym.observation.ProtoItemStackViewBK\n2io.github.mousemeya.gymcraft.gym.observation.protoB\x13ItemEntityViewProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gymcraft.gym.observation.common.item_entity_view_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2io.github.mousemeya.gymcraft.gym.observation.protoB\023ItemEntityViewProtoP\001'
  _globals['_PROTOITEMENTITYVIEW']._serialized_start=140
  _globals['_PROTOITEMENTITYVIEW']._serialized_end=305
# @@protoc_insertion_point(module_scope)
