# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gymcraft/gym/observation/common/item_stack_view.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gymcraft/gym/observation/common/item_stack_view.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5gymcraft/gym/observation/common/item_stack_view.proto\x12\x18gymcraft.gym.observation\"M\n\x12ProtoItemStackView\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x0b\n\x03nbt\x18\x05 \x01(\tJ\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05\x42J\n2io.github.mousemeya.gymcraft.gym.observation.protoB\x12ItemStackViewProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gymcraft.gym.observation.common.item_stack_view_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2io.github.mousemeya.gymcraft.gym.observation.protoB\022ItemStackViewProtoP\001'
  _globals['_PROTOITEMSTACKVIEW']._serialized_start=83
  _globals['_PROTOITEMSTACKVIEW']._serialized_end=160
# @@protoc_insertion_point(module_scope)
