# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gymcraft/gym/observation/components/chat.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gymcraft/gym/observation/components/chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.gymcraft/gym/observation/components/chat.proto\x12\x18gymcraft.gym.observation\"F\n\x10ProtoChatMessage\x12\x11\n\tgame_tick\x18\x01 \x01(\x03\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"O\n\x0fProtoRecentChat\x12<\n\x08messages\x18\x01 \x03(\x0b\x32*.gymcraft.gym.observation.ProtoChatMessageBA\n2io.github.mousemeya.gymcraft.gym.observation.protoB\tChatProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gymcraft.gym.observation.components.chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2io.github.mousemeya.gymcraft.gym.observation.protoB\tChatProtoP\001'
  _globals['_PROTOCHATMESSAGE']._serialized_start=76
  _globals['_PROTOCHATMESSAGE']._serialized_end=146
  _globals['_PROTORECENTCHAT']._serialized_start=148
  _globals['_PROTORECENTCHAT']._serialized_end=227
# @@protoc_insertion_point(module_scope)
