# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gymcraft/gym/observation/components/menu.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gymcraft/gym/observation/components/menu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gymcraft.gym.observation.common import slot_pb2 as gymcraft_dot_gym_dot_observation_dot_common_dot_slot__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.gymcraft/gym/observation/components/menu.proto\x12\x18gymcraft.gym.observation\x1a*gymcraft/gym/observation/common/slot.proto\"\x8f\x02\n\x14ProtoMenuObservation\x12\x0c\n\x04open\x18\x01 \x01(\x08\x12\x12\n\nsession_id\x18\x02 \x01(\x04\x12\x11\n\tmenu_type\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x36\n\x05slots\x18\x05 \x03(\x0b\x32\'.gymcraft.gym.observation.ProtoSlotView\x12?\n\nproperties\x18\x06 \x03(\x0b\x32+.gymcraft.gym.observation.ProtoMenuProperty\x12:\n\x07\x62uttons\x18\x07 \x03(\x0b\x32).gymcraft.gym.observation.ProtoMenuButton\"C\n\x11ProtoMenuProperty\x12\x11\n\tdata_slot\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x05\"C\n\x0fProtoMenuButton\x12\x11\n\tbutton_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x03 \x01(\x08\x42\x41\n2io.github.mousemeya.gymcraft.gym.observation.protoB\tMenuProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gymcraft.gym.observation.components.menu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2io.github.mousemeya.gymcraft.gym.observation.protoB\tMenuProtoP\001'
  _globals['_PROTOMENUOBSERVATION']._serialized_start=121
  _globals['_PROTOMENUOBSERVATION']._serialized_end=392
  _globals['_PROTOMENUPROPERTY']._serialized_start=394
  _globals['_PROTOMENUPROPERTY']._serialized_end=461
  _globals['_PROTOMENUBUTTON']._serialized_start=463
  _globals['_PROTOMENUBUTTON']._serialized_end=530
# @@protoc_insertion_point(module_scope)
