# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gymcraft/gym/observation/components/nearby_items.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gymcraft/gym/observation/components/nearby_items.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gymcraft.gym.observation.common import item_entity_view_pb2 as gymcraft_dot_gym_dot_observation_dot_common_dot_item__entity__view__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6gymcraft/gym/observation/components/nearby_items.proto\x12\x18gymcraft.gym.observation\x1a\x36gymcraft/gym/observation/common/item_entity_view.proto\"P\n\x10ProtoNearbyItems\x12<\n\x05items\x18\x01 \x03(\x0b\x32-.gymcraft.gym.observation.ProtoItemEntityViewBH\n2io.github.mousemeya.gymcraft.gym.observation.protoB\x10NearbyItemsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gymcraft.gym.observation.components.nearby_items_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2io.github.mousemeya.gymcraft.gym.observation.protoB\020NearbyItemsProtoP\001'
  _globals['_PROTONEARBYITEMS']._serialized_start=140
  _globals['_PROTONEARBYITEMS']._serialized_end=220
# @@protoc_insertion_point(module_scope)
