# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gymcraft/gym/observation/components/world.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gymcraft/gym/observation/components/world.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/gymcraft/gym/observation/components/world.proto\x12\x18gymcraft.gym.observation\"\xc3\x01\n\x0fProtoWorldState\x12\x10\n\x08\x64\x61y_time\x18\x01 \x01(\x03\x12\x0f\n\x07raining\x18\x02 \x01(\x08\x12\x12\n\nthundering\x18\x03 \x01(\x08\x12\x11\n\tdimension\x18\x04 \x01(\t\x12\r\n\x05\x62iome\x18\x05 \x01(\t\x12\x11\n\tstructure\x18\x06 \x01(\t\x12\x44\n\nstructures\x18\x07 \x03(\x0b\x32\x30.gymcraft.gym.observation.ProtoStructureLocation\"a\n\x16ProtoStructureLocation\x12\x14\n\x0cstructure_id\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\t\n\x01z\x18\x04 \x01(\x05\x12\x10\n\x08\x64istance\x18\x05 \x01(\x01\x42G\n2io.github.mousemeya.gymcraft.gym.observation.protoB\x0fWorldStateProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gymcraft.gym.observation.components.world_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2io.github.mousemeya.gymcraft.gym.observation.protoB\017WorldStateProtoP\001'
  _globals['_PROTOWORLDSTATE']._serialized_start=78
  _globals['_PROTOWORLDSTATE']._serialized_end=273
  _globals['_PROTOSTRUCTURELOCATION']._serialized_start=275
  _globals['_PROTOSTRUCTURELOCATION']._serialized_end=372
# @@protoc_insertion_point(module_scope)
