# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gymcraft/gym/rpc/env_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gymcraft/gym/rpc/env_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gymcraft.gym.action import action_pb2 as gymcraft_dot_gym_dot_action_dot_action__pb2
from gymcraft.gym.observation import observation_pb2 as gymcraft_dot_gym_dot_observation_dot_observation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"gymcraft/gym/rpc/env_service.proto\x12\x10gymcraft.gym.rpc\x1a gymcraft/gym/action/action.proto\x1a*gymcraft/gym/observation/observation.proto\"%\n\x0e\x43onnectRequest\x12\x13\n\x0b\x65ntity_uuid\x18\x01 \x01(\t\"\x87\x01\n\x0f\x43onnectResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x13\n\x0b\x65ntity_uuid\x18\x02 \x01(\t\x12\x10\n\x08metadata\x18\x03 \x01(\t\x12\x19\n\x11\x61\x63tion_space_json\x18\x04 \x01(\t\x12\x1e\n\x16observation_space_json\x18\x05 \x01(\t\"O\n\x0cResetRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\x04seed\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x0f\n\x07options\x18\x03 \x01(\tB\x07\n\x05_seed\"`\n\rResetResponse\x12\x41\n\x0bobservation\x18\x01 \x01(\x0b\x32,.gymcraft.gym.observation.ProtoMcObservation\x12\x0c\n\x04info\x18\x02 \x01(\t\"}\n\x0bStepRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x33\n\x07\x61\x63tions\x18\x03 \x03(\x0b\x32\".gymcraft.gym.action.ProtoMcAction\x12\x17\n\x0ftimeout_seconds\x18\x04 \x01(\x02J\x04\x08\x02\x10\x03R\x06\x61\x63tion\"\x96\x01\n\x0cStepResponse\x12\x41\n\x0bobservation\x18\x01 \x01(\x0b\x32,.gymcraft.gym.observation.ProtoMcObservation\x12\x0e\n\x06reward\x18\x02 \x01(\x01\x12\x12\n\nterminated\x18\x03 \x01(\x08\x12\x11\n\ttruncated\x18\x04 \x01(\x08\x12\x0c\n\x04info\x18\x05 \x01(\t\")\n\x13\x43loseSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"&\n\x14\x43loseSessionResponse\x12\x0e\n\x06\x63losed\x18\x01 \x01(\x08\x32\xcf\x02\n\rGymEnvService\x12N\n\x07\x43onnect\x12 .gymcraft.gym.rpc.ConnectRequest\x1a!.gymcraft.gym.rpc.ConnectResponse\x12H\n\x05Reset\x12\x1e.gymcraft.gym.rpc.ResetRequest\x1a\x1f.gymcraft.gym.rpc.ResetResponse\x12\x45\n\x04Step\x12\x1d.gymcraft.gym.rpc.StepRequest\x1a\x1e.gymcraft.gym.rpc.StepResponse\x12]\n\x0c\x43loseSession\x12%.gymcraft.gym.rpc.CloseSessionRequest\x1a&.gymcraft.gym.rpc.CloseSessionResponseB?\n*io.github.mousemeya.gymcraft.gym.rpc.protoB\x0f\x45nvServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gymcraft.gym.rpc.env_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*io.github.mousemeya.gymcraft.gym.rpc.protoB\017EnvServiceProtoP\001'
  _globals['_CONNECTREQUEST']._serialized_start=134
  _globals['_CONNECTREQUEST']._serialized_end=171
  _globals['_CONNECTRESPONSE']._serialized_start=174
  _globals['_CONNECTRESPONSE']._serialized_end=309
  _globals['_RESETREQUEST']._serialized_start=311
  _globals['_RESETREQUEST']._serialized_end=390
  _globals['_RESETRESPONSE']._serialized_start=392
  _globals['_RESETRESPONSE']._serialized_end=488
  _globals['_STEPREQUEST']._serialized_start=490
  _globals['_STEPREQUEST']._serialized_end=615
  _globals['_STEPRESPONSE']._serialized_start=618
  _globals['_STEPRESPONSE']._serialized_end=768
  _globals['_CLOSESESSIONREQUEST']._serialized_start=770
  _globals['_CLOSESESSIONREQUEST']._serialized_end=811
  _globals['_CLOSESESSIONRESPONSE']._serialized_start=813
  _globals['_CLOSESESSIONRESPONSE']._serialized_end=851
  _globals['_GYMENVSERVICE']._serialized_start=854
  _globals['_GYMENVSERVICE']._serialized_end=1189
# @@protoc_insertion_point(module_scope)
