# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gymcraft.gym.rpc import env_service_pb2 as gymcraft_dot_gym_dot_rpc_dot_env__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gymcraft/gym/rpc/env_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GymEnvServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/gymcraft.gym.rpc.GymEnvService/Connect',
                request_serializer=gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.ConnectRequest.SerializeToString,
                response_deserializer=gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/gymcraft.gym.rpc.GymEnvService/Reset',
                request_serializer=gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.ResetRequest.SerializeToString,
                response_deserializer=gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/gymcraft.gym.rpc.GymEnvService/Step',
                request_serializer=gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.StepRequest.SerializeToString,
                response_deserializer=gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.StepResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/gymcraft.gym.rpc.GymEnvService/CloseSession',
                request_serializer=gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.CloseSessionResponse.FromString,
                _registered_method=True)


class GymEnvServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GymEnvServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.ConnectRequest.FromString,
                    response_serializer=gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.ConnectResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.ResetRequest.FromString,
                    response_serializer=gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.ResetResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.StepRequest.FromString,
                    response_serializer=gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.StepResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.CloseSessionRequest.FromString,
                    response_serializer=gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.CloseSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gymcraft.gym.rpc.GymEnvService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gymcraft.gym.rpc.GymEnvService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GymEnvService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gymcraft.gym.rpc.GymEnvService/Connect',
            gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.ConnectRequest.SerializeToString,
            gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gymcraft.gym.rpc.GymEnvService/Reset',
            gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.ResetRequest.SerializeToString,
            gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gymcraft.gym.rpc.GymEnvService/Step',
            gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.StepRequest.SerializeToString,
            gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gymcraft.gym.rpc.GymEnvService/CloseSession',
            gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.CloseSessionRequest.SerializeToString,
            gymcraft_dot_gym_dot_rpc_dot_env__service__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
