# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gymcraft/gym/observation/observation.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gymcraft/gym/observation/observation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*gymcraft/gym/observation/observation.proto\x12\x18gymcraft.gym.observation\x1a\x19google/protobuf/any.proto\"\x92\x01\n\x16ProtoObservationHeader\x12\x16\n\x0eschema_version\x18\x01 \x01(\x05\x12\x11\n\tgame_tick\x18\x02 \x01(\x03\x12\x10\n\x08\x61gent_id\x18\x03 \x01(\t\x12\x1a\n\x12last_action_status\x18\x04 \x01(\t\x12\x1f\n\x17last_action_description\x18\x05 \x01(\t\"\xf1\x01\n\x12ProtoMcObservation\x12@\n\x06header\x18\x01 \x01(\x0b\x32\x30.gymcraft.gym.observation.ProtoObservationHeader\x12P\n\ncomponents\x18\x02 \x03(\x0b\x32<.gymcraft.gym.observation.ProtoMcObservation.ComponentsEntry\x1aG\n\x0f\x43omponentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\x42H\n2io.github.mousemeya.gymcraft.gym.observation.protoB\x10ObservationProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gymcraft.gym.observation.observation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2io.github.mousemeya.gymcraft.gym.observation.protoB\020ObservationProtoP\001'
  _globals['_PROTOMCOBSERVATION_COMPONENTSENTRY']._loaded_options = None
  _globals['_PROTOMCOBSERVATION_COMPONENTSENTRY']._serialized_options = b'8\001'
  _globals['_PROTOOBSERVATIONHEADER']._serialized_start=100
  _globals['_PROTOOBSERVATIONHEADER']._serialized_end=246
  _globals['_PROTOMCOBSERVATION']._serialized_start=249
  _globals['_PROTOMCOBSERVATION']._serialized_end=490
  _globals['_PROTOMCOBSERVATION_COMPONENTSENTRY']._serialized_start=419
  _globals['_PROTOMCOBSERVATION_COMPONENTSENTRY']._serialized_end=490
# @@protoc_insertion_point(module_scope)
