syntax = "proto3";

package gymcraft.gym.action;

option java_multiple_files = true;
option java_package = "io.github.mousemeya.gymcraft.gym.action.proto";
option java_outer_classname = "ComponentsProto";

message ProtoStepMove {
  float forward = 1;
  float strafe_right = 2;
  float yaw_delta = 3;
  float pitch_delta = 4;
  bool jump = 5;
}

message ProtoMoveTo {
  double x = 1;
  double y = 2;
  double z = 3;
  double stop_distance = 4;
}

message ProtoSetAttackTarget {
  string target_uuid = 1;
  int32 target_entity_id = 2;
}

message ProtoAttackOnce {
  int32 target_entity_id = 1;
}

message ProtoNoop {
}

message ProtoBreakBlock {
  int32 x = 1;
  int32 y = 2;
  int32 z = 3;
}

message ProtoPlaceBlock {
  int32 x = 1;
  int32 y = 2;
  int32 z = 3;
  // 放置时点击的相邻方块面, Direction 3D data value: 0=DOWN 1=UP 2=NORTH 3=SOUTH 4=WEST 5=EAST
  int32 face = 4;
}
